#ENC[AES256_GCM,data:flIIOJzrw/zpMnFAD8Q5fgstE6EMeTqNfYvTTNES/nA4OF61Q6vwXQqmZliRBS5U77aQBd2rcG9G9xxzgAHto3g=,iv:X69TK4wHB4L5cHcLHdwxncXc/oL/EeLsTDQ8QvvfCn4=,tag:ar/rKWUuiGycOZJ3sWcCTg==,type:comment]
#
#ENC[AES256_GCM,data:MpIkPQTfDmW8ecFkDknTaSbG7xDSQnoETmjzQo8Zhd3lZzp0vIPlddpG+3MxaIpsS5ht5Rzz/Uyhdd9Csno9z86Q5h7ju08Hh3WlcGbb/liepV0KwjxmdSgC,iv:Xr5Oh0taj6phgM6tsaYJnHvSTXE2afjQv+hsH1nbVmw=,tag:fhjhdaF5KirpJJmcZTdToA==,type:comment]
#ENC[AES256_GCM,data:vwQXmmet1IHH9pjeXvu9fs3wukt8whEfRlYNMRBY1Dvhx1eNDDfbn/zl4lSJAX3pqWZcyZR8/UE2G9xT6qNwJiWwlYqugiK/Mpaf0YOfd/aAMupvCJYCkX9qK+UnrdEu,iv:W/7Uv68Yra4SQ+pinAfh23kxmaN6yj9eBcnTcdsXFB0=,tag:EeI4B2C7IamhHVD+pOZwiw==,type:comment]
#ENC[AES256_GCM,data:NdlpBmZETTrxchLQe6zrZSnNLjZnJ2o3B7RHodsFBeKdk/QIyuTyNw+VJM4WI9ch7/92eCsSo19pxxFxpK/FJkKsZTFCYVdLV9gB,iv:uBQRZexcdb6+ZwhYrASgu2EUYQnANxx0HvNKCZq9ur4=,tag:J1xCtsauvHAMRGlxshujpA==,type:comment]
server:
    address: ENC[AES256_GCM,data:IhyMymnOESZOndhl,iv:6pxgcmwibcoqPL3ErjVtlT/nMQrc/NyctKaElV5jl9Q=,tag:YkV0xQyc+eQkV30YJoorQA==,type:str]
log:
    level: ENC[AES256_GCM,data:vaYHiw==,iv:6qH1Bs9BRffxAtcLsq9RT2yLGoB3uC6p14fbFGRdZgY=,tag:LcLt//4hNA9+mnzILHIaKQ==,type:str]
#ENC[AES256_GCM,data:20AACGxLEei1Zg5QMom1zKMjSR+urgBmbcyls3QY7G49rstv2ufgpr4FiadFuV6IU+QrH1S/RRR5u56Sn85Ba2bSi0VE4sjHg5aMKZjd2FzwK52MtsKs79TuBSKtAEX2BnDOjahDTNDn9/WWH2vReThlrmPDE0wrKyH15sBx+8D570Xv+rMxoW8iRJiF1+AWOxFUFekpSCnhA+EdBhdDd7EU956Dw+LmY68L8++M38mVLEG7OnO+EvOIzKlNV10elNLgAcPt2P9aqaXVW1cAJTLe9RoNX5zOnCIKnw==,iv:OypfljdswArcveHH5Zc+tYyWGvll3lyfI60Tb13qeS8=,tag:z4pJ9eOgZMsUxo2BZa1GOQ==,type:comment]
session:
    name: ENC[AES256_GCM,data:H5z1wh2OfM1BZcjJpTQ99g==,iv:nVNcIYxTGPGxXW5hh9zeAtn250v6TCLsrllvd8SLjbc=,tag:kIC5nAcNkWX2xuoHr3jgIQ==,type:str]
    expiration: ENC[AES256_GCM,data:t+w=,iv:O7Fo9u6gp8GrCylhxFetRlDyqn+jTYHUXGg0yABV6go=,tag:YpAdWZg+nk66N0IisGRLpw==,type:str]
    inactivity: ENC[AES256_GCM,data:GXvq,iv:GFPau9M6PXMc65p+IaDY4Sl9OV7ooi4+vZ/Asv+Ubbg=,tag:viosJWDjjF8iaiDIf8sYbg==,type:str]
    cookies:
        - domain: ENC[AES256_GCM,data:NRl+5pfxgA8p9yhbh969R4wJtA==,iv:f2SLqLEPsAR0+nU2ZdkzeIcM7eSNERSxqMviJEnrRLQ=,tag:faPMTzY0C1TNYv8XAFbIAg==,type:str]
          authelia_url: ENC[AES256_GCM,data:RQ0MMAcyYOpHmPhLJnQLbhsf6YTJxohaAzwNtv2iB8I=,iv:TaXT6b8aCrg+XVxRXoGcruSjKbDa1YovPkG7d5iw80M=,tag:RkEoi/v3lVk4plOLrNsXfQ==,type:str]
          default_redirection_url: ENC[AES256_GCM,data:WStuQkZMkCapfoOcd1G5YU75meqxgqlO5j78o3xVR7N7/faipg==,iv:QS8n7kHxnUh3qlaHk49zaUS95TgwbrpuHTU4HF/4Z1w=,tag:DnA4JwR7niYvpUTqWvo7Lg==,type:str]
    #ENC[AES256_GCM,data:cVTfiEqh+qLs609LlcA4JYkvWuL5JsINL0fD2BNVvHj9PnEzXWgplK3inF6KJrSzgWcY1ZIQWByspbORQ/Q=,iv:iP3xCVi5vc55fskoLg/Xr0J0sI3E5uR2Ow+HbVATX6s=,tag:2lf8mEvdGPlH5NAvmGg3cw==,type:comment]
#ENC[AES256_GCM,data:89EmPtUDDXMhwvUPxX1B9J7zaczTGs5DF2ZEZkuH+o1wxMBVcuUg/igGMXF3Gnuo071R6f9jJY7wuSPN/cE4HMvVJ0nHD6EWb+9r4gZsagdPmxe/GJkEYlHvkfKvAQXx1YwNNrY5v+BxzhjteXspvGbExeDnWMgsG5blXvWHw4I+y7xtzv5LxyFE,iv:YV/2ED5Hu+yfdFcKtWJvcH/SjEqJ+OEc1LrZwxI+WSQ=,tag:lPaAMdnn78dVU9nJnIp6rA==,type:comment]
storage:
    local:
        path: ENC[AES256_GCM,data:BVRhx+eUJtFpBHUNh34nnz8H,iv:kOU51XbFRssDtqJWrOXsBwjqb2ckNbQt/ktU1GJRqm0=,tag:PBFk188gJmRcn9lN2o9dyg==,type:str]
    #ENC[AES256_GCM,data:HqQ6Vhru8jot8CS9vXp00+ioZ/kPIPYGRb04ANNmKJIYcshUtZvPhPbpQBaiI8o0mgzMLK6CVi7K4AJDgipSfTsvrCWUJuMVZfya3bPr,iv:EgwwKWQp1rB2gATmeXJyBkZ1qbTgUeg3u7uBfJbu3yg=,tag:mCnxuxIzLCVYi3fXxj/9pw==,type:comment]
#ENC[AES256_GCM,data:RNEltdyhP/iyIuLGDJ5INbmAj9EYOfWFdKT+t0ugiNIOPSV82M247b90LeTOMq3dl9W85YZ2MNtguiYhYaNAddmir1+ijDafjK3KaHrMmJOw1Jh2MOlFA1R2xZ0donXW9ishufkYvb3wPaq9cM+fNndwrxx5MkVCZT1Atblm+vHdt0GD,iv:p1a5FbvH4HHVn3zpN2nNGN6qVf4BPFc441aV9IGVFv8=,tag:vkgO6qadxKe6WEeSodp66Q==,type:comment]
authentication_backend:
    file:
        path: ENC[AES256_GCM,data:sWFbsKqk0RIfxIRjG0KD61PIY6/QCXQRd9A=,iv:vo5nNnJMriVDqG8Gows2Vff3kDkmw8ti8Teu7vZf11s=,tag:kQgezVxj8E7Kkwvz5fEcIQ==,type:str]
        password:
            algorithm: ENC[AES256_GCM,data:WYyhdgCQpmQ=,iv:PMLq0zMOR+1ZO7UrkABJWS1i6NQgXoLSqSBdeoq31+Q=,tag:aliKw9PYH+JUsHtTZ5JTRw==,type:str]
            iterations: ENC[AES256_GCM,data:mA==,iv:kOTdTm0fyboWsmeLK4rHXIOaCBH0irVAStkl7QLCvbU=,tag:YaTvOtwD3vDuIcyJp5+zvA==,type:int]
            salt_length: ENC[AES256_GCM,data:myE=,iv:zybmY9Pc6DakCXakJC3mYPKdXHLcwO0XxeejxmBzRbg=,tag:eIgOayMVIZm7C++QnDr1Iw==,type:int]
            parallelism: ENC[AES256_GCM,data:/Q==,iv:erSd4WibAGFYEeX2niUHMHs2CopQ6DNn3JmObuUGO1E=,tag:7D3TEVVjJ5Pq1/mVoy7o8Q==,type:int]
            memory: ENC[AES256_GCM,data:6F8pS9o=,iv:M0WWgwtIT5+Br0CGxUD4CmoyJJETzG3Aar+7A+oBrZU=,tag:pUlQGRrOOfO5/DAZFkzYJg==,type:int]
#ENC[AES256_GCM,data:lZ40Q2WPBE29xGpqIi/upJ8B6bATo+q5YYQf5+4Z3K499l2PZ1YsZ/RyZWW7TnRAmIck3uvyDQ3uFQ6zDT6V5AR8YUySS53eecWrxeTD2LRFTqhLpDqxt8IehkSU+J3hIb/Ldy4gBfOVOhnvT0jrHncORfHpDHPqsmnbCrnmVe0Ai6q5ym/x0/EPAhQMKe/AVHiE1OyNiUwrRw75bBsDpRBNx432Z27HwezcrU2rXG4VnJ/eVZeBWOoY4tjkL33jlhm7,iv:Ud8eLByf72fPkEBr4MEuGH+49xlmef+iqKbFoEXnNCQ=,tag:d2eG5AWcIZVQy76YnyXiqw==,type:comment]
access_control:
    default_policy: ENC[AES256_GCM,data:vxGsLQ==,iv:bi5IjsgVWKE6x3dzREWueKFX6p7K28IYYwj5iZl73cA=,tag:xvDq6EWzE+t1q+p9L4Ae+w==,type:str]
    rules:
        - domain: ENC[AES256_GCM,data:2UdvKsTzRAtwLta7dGBhVQK4cDCHFspQMuGyrIA=,iv:Tad8Ac/cCHztezjbcYrNnBJHjnVMhYRpWSLQ+9i/fcQ=,tag:y+D22DwmBbLq9vdQc09ejg==,type:str]
          policy: ENC[AES256_GCM,data:eHf3xuzsBuv9aw==,iv:LBmFFKBPWuPRdi7Vus3AI4ENCHO0vwsKO0yHOG28J80=,tag:YdD3NlaWNeeu7dbIkX7LrA==,type:str]
#ENC[AES256_GCM,data:5I+kmCXB7qyhO4scv0aFnv0XGW4xZszeEqLgCSBPKRKY4H7xL4wysSqkLgfSRaTBLe+32Pwp9kD64nyBNlwcO2CCX2AomsaLJX7jOcCHs2NCwDb2RSr6nR+e0/NSj0j07/5ELU6NOlkaP0mjJcAmA8kM1MKVtaL2oIxBP7WnCOzPfKJoV2hqFQDLLXb2Pat+J4aMs9At6pNCGdX8mMgo4g==,iv:AfCs00uJcISies2CZBHVr+5CvR7Ey33KZngzMA2dc6c=,tag:Z4XL1IttU4OdPWc1SA3JXA==,type:comment]
notifier:
    filesystem:
        filename: ENC[AES256_GCM,data:SD+lP+dGTdI/o+j5+YOCpq0k5RKdVyHT,iv:W4pNZSHm2EzzPlC6lLtS2IOPTeKthPwHfKI8GnCpTrs=,tag:0/lUoqOB5E7RuQBBRvAW/A==,type:str]
#ENC[AES256_GCM,data:c7fcb43RZW3YZzCgYvfdEaD1+CWP138+b8YbEuHnAXCBxSfEFaZI+j2AtPpXZvNAFHeFrzsTIVETY/w8BJPOUjuGvKDQQJQY07i5dujcmObL6p5zzOApbi73II0iuFXRn3Uc9BDAmNR4IHOE1F5n1Z9oR0d4ku/YYAiPfI3VIP3LEcviAW75mDGST5R8LaZCP/nUvvf3uGXH2gjHwAhxMQ4=,iv:tex1u8xFwZ5yB5ahKUjHz1Z0QqbTulqDO/P6xLVrTOQ=,tag:kZyOw8KsSt4FJlq0++L8UQ==,type:comment]
#ENC[AES256_GCM,data:NhKR6F8sWMuWMEe41SgISPDfgZqgPDEyV/OS44MuTIt93O2YeZC1N8Pj+A==,iv:AlDTc/jSoLiqAteA9ifzmAarj7Cko6MNdqfKXOgX6ug=,tag:kB/4nq5LPUA1d6TrP0qgtw==,type:comment]
#ENC[AES256_GCM,data:aHXXQIX+T8AUc5nTccWUO7EUvtoCaV2W3NVV8pgh+HBIBOB+5wR9WEvbzc9f4/Y=,iv:TlYFphty/h4xwVP+cw8Ib97eGUxay4dzyIcb1WbPxcE=,tag:EmMY/Gd87W+lB3rhuI1JUA==,type:comment]
#ENC[AES256_GCM,data:4pGmGqreEXjotTrnCn0meBcyWm7Q1p5kVqsGhEJNFrBb2slRp+K8OE1T9P2tkt1bftcALwfx72+H98w=,iv:EUOzLEUJKYB4AnCjFr0aljt+uYE4DKOqSd0fVsWHSMI=,tag:5cfJGcIqtP99vsW13vLYZg==,type:comment]
#ENC[AES256_GCM,data:BkwhfF2Mfm/HJqqP4f7qRN/sTK7gl5wwZIfdPzj6U0QpYAyt3xfIRoptEA7fhIrywHK9hrWzde/BvvlMlBLv6ogVSZo=,iv:dcDeP4SchYr9Fb3QyAzySVoSKkhCskSEbmJ39gx1y+g=,tag:2g+WbBDuEe2zInK3KGbifw==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lau0w4xgfkh9xnn58f2nwt0t4vstva30nht9zcggg2g7ssgq9uqsvd8zmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSM2Y0ZXlPYmFPLzBuYlBK
            TStCR3ZKTjE2THhJQ0k2V3I0S1I3LzlVZW1FClVqWGJ6SkJRenAyM05lbGpZdVpP
            MUVTbFJCajhkMmZGTGRpZWJoYWdFTlEKLS0tIEhzTHczbGtJc215ZUhUeWNiZnI3
            aGdSMDdsOFZvRmw5WGNqTXM4M1QrSUkK4IyhK0QFkXfidnYbRNXo0ySb936v5iyo
            N4EmSmIxiS1ROBfyOpwKLN17UIKJfKDBZza4JNaDoJIS0hODfWRntg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T14:58:51Z"
    mac: ENC[AES256_GCM,data:MpwVo6fsh21YYLvHGIzfMjnOGtzaAVr9lWtWFIgoFz9yjF6D3MXLIkOF7cVM3SR4NMd0obcvjEqZn/tZZ2D4Qyn/LDYKBuXNdQcAhfgdpguDnrLSrTSd7VYD498ik4yh8zHlNt346QpeqIIu13b3kx5QuWWl2WDvgPYzdcQ5gAg=,iv:3y1G8bSTICqcm2eNhtyF5HqI48KGNP25PZJzoSiKilU=,tag:fMGcslBihMXP9ueJ94Fu9Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
